const state={profile:null,results:null,media:null,original:{},dirty:new Set(),user:null,pendingPhoto:null};
const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const api=async(path,options={})=>{const user=window.ariannaIdentity?.currentUser();const token=await user?.jwt();const response=await fetch(`/.netlify/functions/${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...options.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Operazione non riuscita");return body};
const showStatus=(message,error=false)=>{const el=$("#global-status");el.textContent=message;el.classList.toggle("is-error",error);el.classList.add("is-visible");clearTimeout(showStatus.timer);showStatus.timer=setTimeout(()=>el.classList.remove("is-visible"),4200)};
const clone=value=>JSON.parse(JSON.stringify(value));
const markDirty=(key)=>{state.dirty.add(key);localStorage.setItem(`arianna-draft-${key}`,JSON.stringify(state[key]));renderChanges();$("#publish-button").disabled=false};
const clearDrafts=()=>{["profile","results","media"].forEach(k=>localStorage.removeItem(`arianna-draft-${k}`));state.dirty.clear();$("#publish-button").disabled=true;renderChanges()};
const getByPath=(obj,path)=>path.split(".").reduce((value,key)=>value?.[key],obj);
const setByPath=(obj,path,value)=>{const parts=path.split(".");let target=obj;parts.slice(0,-1).forEach(key=>{if(target[key]==null)target[key]={};target=target[key]});target[parts.at(-1)]=value};

const contentMap=[
  {page:"Home",url:"/",section:"Hero",fields:[["content.home.hero.screenReaderTitle","Titolo accessibile hero"],["content.home.hero.subcopy","Sottotitolo"],["content.home.hero.subcopyStrong","Claim in evidenza"],["content.home.hero.mobileValues.0","Valore 1"],["content.home.hero.mobileValues.1","Valore 2"],["content.home.hero.mobileValues.2","Valore 3 in evidenza"],["content.home.hero.mobileValues.3","Valore 4"]]},
  {page:"Home",url:"/",section:"I momenti che contano",fields:[["content.home.highlights.kicker","Etichetta"],["content.home.highlights.title","Titolo sezione"],["content.home.highlights.cta","Pulsante verso Media"]]},
  {page:"Home",url:"/",section:"Chi è Arianna",fields:[["content.home.profile.kicker","Etichetta"],["content.home.profile.title","Titolo"],["content.home.profile.paragraph1","Testo 1","textarea"],["content.home.profile.paragraph2","Testo 2","textarea"],["content.home.profile.cta","Pulsante verso Profilo"],["content.home.profile.quote","Citazione sotto la sezione","textarea"]]},
  {page:"Home",url:"/",section:"Yīng · 鹰",fields:[["content.home.ying.kicker","Etichetta"],["content.home.ying.title","Titolo"],["content.home.ying.meaning","Significato"],["content.home.ying.paragraph1","Testo 1","textarea"],["content.home.ying.paragraph2","Testo 2","textarea"],["content.home.ying.cta","Pulsante verso Yīng"]]},
  {page:"Profilo",url:"/profilo/",section:"SEO",fields:[["content.profilePage.seo.title","Title pagina"],["content.profilePage.seo.description","Meta description","textarea"]]},
  {page:"Profilo",url:"/profilo/",section:"Hero · Crescere sul tatami",fields:[["content.profilePage.hero.titleLine1","Titolo riga 1"],["content.profilePage.hero.titleLine2","Titolo riga 2"],["content.profilePage.hero.quote","Citazione hero","textarea"]]},
  {page:"Profilo",url:"/profilo/",section:"01 · Il mio percorso",fields:[["content.profilePage.journey.kicker","Etichetta"],["content.profilePage.journey.titleLine1","Titolo riga 1"],["content.profilePage.journey.titleLine2","Titolo riga 2"],["content.profilePage.journey.paragraph1","Testo 1","textarea"],["content.profilePage.journey.paragraph2","Testo 2","textarea"]]},
  {page:"Profilo",url:"/profilo/",section:"02 · Valori sportivi",fields:[["content.profilePage.values.kicker","Etichetta"],["content.profilePage.values.items.0.title","Valore 1 · Titolo"],["content.profilePage.values.items.0.text","Valore 1 · Testo"],["content.profilePage.values.items.1.title","Valore 2 · Titolo"],["content.profilePage.values.items.1.text","Valore 2 · Testo"],["content.profilePage.values.items.2.title","Valore 3 · Titolo"],["content.profilePage.values.items.2.text","Valore 3 · Testo"],["content.profilePage.values.items.3.title","Valore 4 · Titolo"],["content.profilePage.values.items.3.text","Valore 4 · Testo"]]},
  {page:"Profilo",url:"/profilo/",section:"03 · La mia guida",fields:[["content.profilePage.coach.kicker","Etichetta"],["content.profilePage.coach.titleLine1","Titolo riga 1"],["content.profilePage.coach.titleLine2","Titolo riga 2"],["content.profilePage.coach.paragraph","Testo","textarea"]]},
  {page:"Profilo",url:"/profilo/",section:"04 · Allenarsi",fields:[["content.profilePage.training.kicker","Etichetta"],["content.profilePage.training.titleLine1","Titolo riga 1"],["content.profilePage.training.titleLine2","Titolo riga 2"],["content.profilePage.training.paragraph1","Testo 1","textarea"],["content.profilePage.training.paragraph2","Testo 2","textarea"]]},
  {page:"Profilo",url:"/profilo/",section:"Il mio obiettivo",fields:[["content.profilePage.objective.kicker","Etichetta"],["content.profilePage.objective.titleLine1","Titolo riga 1"],["content.profilePage.objective.titleLine2","Titolo riga 2"],["content.profilePage.objective.titleLine3","Titolo riga 3"],["content.profilePage.objective.paragraph","Testo","textarea"],["content.profilePage.objective.cta","Pulsante verso Risultati"]]},
  {page:"Yīng",url:"/ying/",section:"SEO",fields:[["content.yingPage.seo.title","Title pagina"],["content.yingPage.seo.description","Meta description","textarea"]]},
  {page:"Yīng",url:"/ying/",section:"Hero · Il mio nome sul tatami",fields:[["content.yingPage.hero.kicker","Etichetta"],["content.yingPage.hero.meaning","Significato"],["content.yingPage.hero.claim","Claim"],["content.yingPage.hero.intro","Testo introduttivo","textarea"]]},
  {page:"Yīng",url:"/ying/",section:"Cosa significa per me",fields:[["content.yingPage.meaning.imageCaption","Didascalia immagine"],["content.yingPage.meaning.kicker","Etichetta"],["content.yingPage.meaning.titleLine1","Titolo riga 1"],["content.yingPage.meaning.titleLine2","Titolo riga 2"],["content.yingPage.meaning.paragraph1","Testo 1","textarea"],["content.yingPage.meaning.paragraph2","Testo 2","textarea"]]},
  {page:"Yīng",url:"/ying/",section:"Perché l’ho scelto",fields:[["content.yingPage.choice.kicker","Etichetta"],["content.yingPage.choice.titleLine1","Titolo riga 1"],["content.yingPage.choice.titleLine2","Titolo riga 2"],["content.yingPage.choice.paragraph1","Testo 1","textarea"],["content.yingPage.choice.paragraph2","Testo 2","textarea"]]},
  {page:"Yīng",url:"/ying/",section:"Essere Yīng",fields:[["content.yingPage.journey.kicker","Etichetta"],["content.yingPage.journey.title","Titolo"],["content.yingPage.journey.paragraph","Testo","textarea"]]},
  {page:"Risultati",url:"/risultati/",section:"SEO",fields:[["content.resultsPage.seo.title","Title pagina"],["content.resultsPage.seo.description","Meta description","textarea"]]},
  {page:"Risultati",url:"/risultati/",section:"Hero",fields:[["content.resultsPage.hero.kicker","Etichetta"],["content.resultsPage.hero.title","Titolo"],["content.resultsPage.hero.intro","Testo introduttivo","textarea"]]},
  {page:"Risultati",url:"/risultati/",section:"Archivio gare",fields:[["content.resultsPage.archive.kicker","Etichetta"],["content.resultsPage.archive.title","Titolo"],["content.resultsPage.archive.intro","Testo introduttivo","textarea"]]},
  {page:"Risultati",url:"/risultati/",section:"Timeline agonistica",fields:[["content.resultsPage.timeline.kicker","Etichetta"],["content.resultsPage.timeline.title","Titolo"],["content.resultsPage.timeline.items.0.period","Periodo 1"],["content.resultsPage.timeline.items.0.text","Testo 1"],["content.resultsPage.timeline.items.1.period","Periodo 2"],["content.resultsPage.timeline.items.1.text","Testo 2"],["content.resultsPage.timeline.items.2.period","Periodo 3"],["content.resultsPage.timeline.items.2.text","Testo 3"],["content.resultsPage.timeline.items.3.period","Periodo 4"],["content.resultsPage.timeline.items.3.text","Testo 4"]]},
  {page:"Media",url:"/media/",section:"SEO",fields:[["content.mediaPage.seo.title","Title pagina"],["content.mediaPage.seo.description","Meta description","textarea"]]},
  {page:"Media",url:"/media/",section:"Hero",fields:[["content.mediaPage.hero.kicker","Etichetta"],["content.mediaPage.hero.title","Titolo"],["content.mediaPage.hero.intro","Testo introduttivo","textarea"]]},
  {page:"Media",url:"/media/",section:"Gallery fotografica",fields:[["content.mediaPage.gallery.kicker","Etichetta"],["content.mediaPage.gallery.title","Titolo"],["content.mediaPage.gallery.intro","Testo introduttivo","textarea"]]},
  {page:"Media",url:"/media/",section:"Video",fields:[["content.mediaPage.video.kicker","Etichetta"],["content.mediaPage.video.title","Titolo"],["content.mediaPage.video.intro","Testo introduttivo","textarea"]]}
];

function activateView(name){$$('[data-view]').forEach(b=>{b.toggleAttribute('aria-current',b.dataset.view===name);if(b.dataset.view===name)b.setAttribute('aria-current','page')});$$('.admin-view').forEach(v=>v.classList.toggle('is-active',v.id===`view-${name}`));const active=$(`#view-${name}`);$("#view-title").textContent=active?.dataset.title||"Console";$("#admin-sidebar").classList.remove("is-open");$("#mobile-menu").setAttribute("aria-expanded","false");window.scrollTo({top:0,behavior:"smooth"})}

async function loadContent(){showStatus("Caricamento dei contenuti…");const data=await api("admin-content");state.original={profile:clone(data.profile),results:clone(data.results),media:clone(data.media)};["profile","results","media"].forEach(key=>{const draft=localStorage.getItem(`arianna-draft-${key}`);state[key]=draft?JSON.parse(draft):clone(data[key]);if(draft)state.dirty.add(key)});fillProfile();renderResults();renderMedia();renderStats();renderCounts();renderChanges();$("#publish-button").disabled=state.dirty.size===0;showStatus(state.dirty.size?"Bozze locali ripristinate":"Contenuti aggiornati")}

function renderContentEditor(){const f=$("#profile-form"),panel=$(".form-panel",f);if(!panel||!state.profile?.content)return;["summary","origin"].forEach(name=>{const field=f.elements.namedItem(name);if(field?.closest("label"))field.closest("label").hidden=true});let root=$("#site-copy-editor",f);if(!root){root=document.createElement("section");root.id="site-copy-editor";root.className="site-copy-editor";panel.insertBefore(root,panel.querySelector(".save-row"));const style=document.createElement("style");style.textContent=`.site-copy-editor{display:grid;gap:18px;margin-top:26px}.copy-page{border:1px solid rgba(20,20,20,.12);border-radius:12px;padding:18px;background:rgba(255,255,255,.45)}.copy-page__head{display:flex;justify-content:space-between;gap:16px;align-items:end;margin-bottom:14px}.copy-page__head strong{display:block;font-size:1rem}.copy-page__head small{color:#6d675e}.copy-section{margin-top:14px;padding-top:14px;border-top:1px solid rgba(20,20,20,.1)}.copy-section h3{margin:0 0 12px;font-size:.86rem}.copy-field{display:block;margin:0 0 12px}.copy-field>span{display:block;font-weight:700}.copy-field small{display:block;margin:4px 0 6px;color:#756f66;font-size:.72rem}.copy-field input,.copy-field textarea{width:100%}`;document.head.append(style)}const groups=new Map();contentMap.forEach(item=>{const key=`${item.page}|${item.url}`;if(!groups.has(key))groups.set(key,{page:item.page,url:item.url,sections:[]});groups.get(key).sections.push(item)});root.innerHTML=[...groups.values()].map(group=>`<article class="copy-page"><header class="copy-page__head"><div><strong>Pagina ${escapeHtml(group.page)}</strong><small>${escapeHtml(group.url)}</small></div><a class="text-button" href="${escapeHtml(group.url)}" target="_blank" rel="noopener">Apri pagina</a></header>${group.sections.map(section=>`<section class="copy-section"><h3>Sezione · ${escapeHtml(section.section)}</h3>${section.fields.map(([path,label,type])=>`<label class="copy-field"><span>${escapeHtml(label)}</span><small>${escapeHtml(group.page)} → ${escapeHtml(section.section)}</small>${type==="textarea"?`<textarea rows="3" data-content-path="${escapeHtml(path)}"></textarea>`:`<input data-content-path="${escapeHtml(path)}" />`}</label>`).join("")}</section>`).join("")}</article>`).join("");$$('[data-content-path]',root).forEach(field=>field.value=getByPath(state.profile,field.dataset.contentPath)??"")}
function fillProfile(){const f=$("#profile-form");Object.entries(state.profile||{}).forEach(([key,value])=>{const field=f.elements.namedItem(key);if(field&&!Array.isArray(value)&&typeof value!=="object")field.value=value??""});renderContentEditor();updateProfilePreview()}
function profileFromForm(){const f=$("#profile-form");const next=clone(state.profile);["name","category","club","coach","discipline","summary","origin"].forEach(k=>{const field=f.elements.namedItem(k);if(field)next[k]=field.value.trim()});next.startedIn=Number(f.elements.namedItem("startedIn").value)||state.profile.startedIn;$$('[data-content-path]',f).forEach(field=>setByPath(next,field.dataset.contentPath,field.value.trim()));return next}
function updateProfilePreview(){const p=profileFromForm();$("#profile-preview-name").textContent=p.name;$("#profile-preview-summary").textContent=p.content?.home?.profile?.paragraph1||p.summary;$("#profile-preview-discipline").textContent=p.discipline;$("#profile-preview-category").textContent=p.category}

function flattenResults(){return (state.results?.resultsByYear||[]).flatMap((group,yearIndex)=>group.competitions.map((competition,competitionIndex)=>({year:group.year,yearIndex,competitionIndex,...competition})))}
function renderResults(){const rows=flattenResults();const yearSelect=$("#result-year-filter");const selected=yearSelect.value;yearSelect.innerHTML='<option value="">Tutti gli anni</option>'+[...new Set(rows.map(r=>r.year))].sort((a,b)=>b-a).map(y=>`<option>${y}</option>`).join("");yearSelect.value=selected;const query=$("#result-search").value.toLowerCase();const year=yearSelect.value;const filtered=rows.filter(r=>(!year||String(r.year)===year)&&(!query||`${r.event} ${r.place}`.toLowerCase().includes(query)));$("#results-table").innerHTML=filtered.map(r=>`<tr><td>${r.year}</td><td>${escapeHtml(r.event)}</td><td>${escapeHtml(r.place||"—")}</td><td><div class="medal-badges">${r.results.map(x=>`<span class="medal-badge">${medalLabel(x.medal)} · ${escapeHtml(x.discipline)}</span>`).join("")}</div></td><td><div class="table-actions"><button type="button" data-edit-result="${r.yearIndex}:${r.competitionIndex}">Modifica</button><button type="button" data-archive-result="${r.yearIndex}:${r.competitionIndex}">Archivia</button></div></td></tr>`).join("");$("#results-empty").hidden=filtered.length>0;$$('[data-edit-result]').forEach(b=>b.onclick=()=>openResult(...b.dataset.editResult.split(':').map(Number)));$$('[data-archive-result]').forEach(b=>b.onclick=()=>archiveResult(...b.dataset.archiveResult.split(':').map(Number)))}
function medalLabel(medal){return medal==="gold"?"Oro":medal==="silver"?"Argento":medal==="bronze"?"Bronzo":"Piazzamento"}
function addResultLine(value={discipline:"",medal:"gold"}){const row=document.createElement("div");row.className="result-line";row.innerHTML=`<input name="discipline" aria-label="Disciplina" value="${escapeHtml(value.discipline)}" required><select name="medal" aria-label="Medaglia"><option value="gold">Oro</option><option value="silver">Argento</option><option value="bronze">Bronzo</option><option value="placement">Piazzamento</option></select><button type="button" aria-label="Rimuovi disciplina">×</button>`;row.querySelector("select").value=value.medal;row.querySelector("button").onclick=()=>row.remove();$("#result-lines").append(row)}
function openResult(yearIndex=-1,competitionIndex=-1){const form=$("#result-form");form.reset();$("#result-lines").innerHTML="";form.elements.yearIndex.value=yearIndex;form.elements.competitionIndex.value=competitionIndex;if(yearIndex>=0){const group=state.results.resultsByYear[yearIndex],item=group.competitions[competitionIndex];form.elements.year.value=group.year;form.elements.event.value=item.event;form.elements.place.value=item.place||"";item.results.forEach(addResultLine);$("#result-dialog-title").textContent="Modifica risultato"}else{form.elements.year.value=new Date().getFullYear();addResultLine();$("#result-dialog-title").textContent="Aggiungi risultato"}$("#result-dialog").showModal()}
function saveResult(){const f=$("#result-form");if(!f.reportValidity())return false;const year=Number(f.elements.year.value);const item={event:f.elements.event.value.trim(),place:f.elements.place.value.trim(),results:$$('.result-line',f).map(row=>({discipline:row.querySelector('[name=discipline]').value.trim(),medal:row.querySelector('[name=medal]').value}))};const yi=Number(f.elements.yearIndex.value),ci=Number(f.elements.competitionIndex.value);if(yi>=0){const oldYear=state.results.resultsByYear[yi];if(oldYear.year===year)oldYear.competitions[ci]=item;else{oldYear.competitions.splice(ci,1);addCompetition(year,item)}}else addCompetition(year,item);state.results.resultsByYear=state.results.resultsByYear.filter(y=>y.competitions.length).sort((a,b)=>a.year-b.year);recalculateResults();markDirty("results");renderResults();renderStats();renderCounts();showStatus("Risultato salvato in bozza");return true}
function addCompetition(year,item){let group=state.results.resultsByYear.find(y=>y.year===year);if(!group){group={year,totals:{gold:0,silver:0,bronze:0},competitions:[]};state.results.resultsByYear.push(group)}group.competitions.push(item)}
function archiveResult(yi,ci){if(!confirm("Archiviare questa competizione? Potrai recuperarla dalla cronologia Git."))return;state.results.resultsByYear[yi].competitions.splice(ci,1);state.results.resultsByYear=state.results.resultsByYear.filter(y=>y.competitions.length);recalculateResults();markDirty("results");renderResults();renderStats();renderCounts();showStatus("Competizione archiviata nella bozza")}
function recalculateResults(){let gold=0,silver=0,bronze=0;for(const group of state.results.resultsByYear){const totals={gold:0,silver:0,bronze:0};group.competitions.flatMap(c=>c.results).forEach(r=>{if(totals[r.medal]!==undefined)totals[r.medal]++});group.totals=totals;gold+=totals.gold;silver+=totals.silver;bronze+=totals.bronze}const total=gold+silver+bronze;state.results.medalSummary={gold,silver,bronze,total};const competitions=state.results.resultsByYear.reduce((n,y)=>n+y.competitions.length,0);const years=Math.max(1,new Date().getFullYear()-(state.profile?.startedIn||new Date().getFullYear())+1);state.results.heroStats=[{id:"years",value:String(years),label:"anni di pratica",icon:"stat-years.svg",isPlaceholder:false},{id:"competitions",value:String(competitions),label:"competizioni",icon:"stat-trophy.svg",isPlaceholder:false},{id:"medals",value:String(total),label:"medaglie vinte",icon:"stat-medal-silver.svg",isPlaceholder:false},{id:"gold",value:String(gold),label:"medaglie d'oro",icon:"stat-medal.svg",isPlaceholder:false}]}

function youtubeId(url){try{const u=new URL(url);if(u.hostname.includes("youtu.be"))return u.pathname.slice(1);if(u.pathname.startsWith("/shorts/"))return u.pathname.split("/")[2];return u.searchParams.get("v")}catch{return null}}
function renderMedia(){const photos=(state.media||[]).filter(m=>m.tipo==="foto"&&m.visibile&&!m.isPlaceholder),videos=(state.media||[]).filter(m=>m.tipo==="video");$("#photos-grid").innerHTML=photos.map(m=>`<article class="media-card"><img src="${escapeHtml(mediaUrl(m))}" alt="${escapeHtml(m.testoAlternativo||"")}"><div class="media-card-content"><strong>${escapeHtml(m.titolo)}</strong><small>${escapeHtml(m.dettaglio||"")}</small><div class="media-card-actions"><span class="status-tag">${m.inEvidenza?"Home · In evidenza":"Gallery"}</span><button class="text-button" type="button" data-highlight-media="${escapeHtml(m.id)}">${m.inEvidenza?"Rimuovi dalla Home":"Mostra in Home"}</button><button class="text-button" type="button" data-remove-media="${escapeHtml(m.id)}">Archivia</button></div></div></article>`).join("");$("#photos-empty").hidden=photos.length>0;$("#videos-list").innerHTML=videos.map(m=>{const id=youtubeId(m.urlYouTube);return `<article class="video-row"><img class="video-thumb" src="${id?`https://i.ytimg.com/vi/${id}/mqdefault.jpg`:""}" alt=""><span><strong>${escapeHtml(m.titolo)}</strong><small>${escapeHtml(m.dettaglio||"")} · ${m.anno||""}</small></span><div class="table-actions"><span class="status-tag">${m.inEvidenza?"Home · In evidenza":"Media"}</span><button type="button" data-highlight-media="${escapeHtml(m.id)}">${m.inEvidenza?"Rimuovi dalla Home":"Mostra in Home"}</button><a class="text-button" href="${escapeHtml(m.urlYouTube)}" target="_blank" rel="noopener">Apri</a><button type="button" data-remove-media="${escapeHtml(m.id)}">Archivia</button></div></article>`}).join("");$("#videos-empty").hidden=videos.length>0;$$('[data-remove-media]').forEach(b=>b.onclick=()=>removeMedia(b.dataset.removeMedia));$$('[data-highlight-media]').forEach(b=>b.onclick=()=>toggleMediaHighlight(b.dataset.highlightMedia))}
function mediaUrl(item){if(item.url)return item.url;if(item.immagine)return `/images/${item.immagine}`;return ""}
function toggleMediaHighlight(id){state.media=state.media.map(m=>m.id===id?{...m,inEvidenza:!m.inEvidenza}:m);markDirty("media");renderMedia();showStatus(state.media.find(m=>m.id===id)?.inEvidenza?"Contenuto aggiunto a “I momenti che contano”":"Contenuto rimosso da “I momenti che contano”")}
function removeMedia(id){if(!confirm("Archiviare questo contenuto?"))return;state.media=state.media.map(m=>m.id===id?{...m,visibile:false}:m);markDirty("media");renderMedia();renderCounts();showStatus("Contenuto archiviato nella bozza")}
function saveVideo(){const f=$("#video-form");if(!f.reportValidity())return false;const url=f.elements.urlYouTube.value.trim();if(!youtubeId(url)){showStatus("Inserisci un link YouTube valido",true);return false}const date=f.elements.data.value;state.media.unshift({id:`video-${Date.now()}`,tipo:"video",titolo:f.elements.titolo.value.trim(),dettaglio:f.elements.dettaglio.value.trim(),data:date||undefined,anno:date?Number(date.slice(0,4)):new Date().getFullYear(),categoria:f.elements.categoria.value,urlYouTube:url,inEvidenza:f.elements.inEvidenza.checked,visibile:true});markDirty("media");renderMedia();renderCounts();showStatus("Video salvato in bozza");return true}

async function optimizeImage(file){const bitmap=await createImageBitmap(file);const max=2560,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/webp",.84));bitmap.close();return blob}
function ensurePhotoHighlightField(){const f=$("#photo-form");if(!f||f.elements.namedItem("inEvidenza"))return;const privacy=f.elements.namedItem("privacyConfirmed")?.closest("label");const label=document.createElement("label");label.className="check-label";label.innerHTML='<input name="inEvidenza" type="checkbox" /> Mostra nella Home, nella sezione “I momenti che contano”';if(privacy)privacy.before(label);else f.querySelector("footer")?.before(label)}
async function savePhoto(){const f=$("#photo-form");if(!f.reportValidity())return false;const button=$("#save-photo");button.disabled=true;button.textContent="Ottimizzazione…";try{const year=Number(f.elements.anno.value)||new Date().getFullYear();const category=f.elements.categoria.value;const blob=await optimizeImage(state.pendingPhoto);const safeName=`${Date.now()}-${slug(f.elements.titolo.value)}.webp`;const signed=await api("admin-media-upload",{method:"POST",body:JSON.stringify({fileName:safeName,contentType:"image/webp",size:blob.size,year,category})});const uploadResponse=await fetch(signed.uploadUrl,{method:"PUT",headers:{"Content-Type":"image/webp"},body:blob});if(!uploadResponse.ok)throw new Error("Upload della foto su archivio non riuscito");state.media.unshift({id:`foto-${Date.now()}`,tipo:"foto",titolo:f.elements.titolo.value.trim(),dettaglio:f.elements.dettaglio.value.trim(),anno:year,categoria:category,url:signed.publicUrl,storageKey:signed.storageKey,testoAlternativo:f.elements.testoAlternativo.value.trim(),inEvidenza:Boolean(f.elements.inEvidenza?.checked),visibile:true,isPlaceholder:false});markDirty("media");renderMedia();renderCounts();showStatus(f.elements.inEvidenza?.checked?"Foto caricata e aggiunta a “I momenti che contano”":"Foto caricata e salvata in Gallery");return true}catch(error){showStatus(error.message,true);return false}finally{button.disabled=false;button.textContent="Carica e salva"}}

function renderStats(){if(!state.results)return;recalculateResults();$("#stats-grid").innerHTML=state.results.heroStats.map(s=>`<article class="stat-card"><span>${escapeHtml(s.value)}</span><strong>${escapeHtml(s.label)}</strong><small>Calcolo automatico</small></article>`).join("")}
function renderCounts(){if(!state.results||!state.media)return;$("#count-results").textContent=flattenResults().length;$("#count-photos").textContent=state.media.filter(m=>m.tipo==="foto"&&m.visibile&&!m.isPlaceholder).length;$("#count-videos").textContent=state.media.filter(m=>m.tipo==="video"&&m.visibile).length}
function renderChanges(){const labels={profile:"Profilo e testi",results:"Risultati e statistiche",media:"Foto e video"};const html=[...state.dirty].map(key=>`<li><span>${labels[key]}</span><span class="status-tag">Bozza</span></li>`).join("");$("#change-list").innerHTML=html;$("#publish-change-list").innerHTML=html;$("#change-list").hidden=!state.dirty.size;$("#draft-empty").hidden=!!state.dirty.size;$("#draft-count").textContent=state.dirty.size?`${state.dirty.size} ${state.dirty.size===1?"area modificata":"aree modificate"}`:"Nessuna modifica"}
async function publish(){const button=$("#confirm-publish");button.disabled=true;button.textContent="Pubblicazione…";try{const files={};for(const key of state.dirty)files[key]=state[key];const result=await api("admin-publish",{method:"POST",body:JSON.stringify({files})});clearDrafts();state.original={profile:clone(state.profile),results:clone(state.results),media:clone(state.media)};$("#publish-dialog").close();showStatus("Modifiche inviate. Il sito sarà aggiornato tra pochi minuti.");renderHistory(result.commitUrls||[])}catch(error){showStatus(`${error.message}. Il sito online è rimasto invariato e la bozza è al sicuro.`,true)}finally{button.disabled=false;button.textContent="Conferma e pubblica"}}
function renderHistory(urls){if(!urls.length)return;$("#history-list").innerHTML=`<li><span><strong>Pubblicazione inviata</strong><small>${new Date().toLocaleString("it-IT")}</small></span><span class="status-tag">Completata</span></li>`}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function slug(value){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||"foto"}

function bind(){ensurePhotoHighlightField();$$('[data-view]').forEach(b=>b.onclick=()=>activateView(b.dataset.view));$$('[data-action-view]').forEach(b=>b.onclick=()=>{activateView(b.dataset.actionView);if(b.dataset.actionView==="results")openResult();if(b.dataset.actionView==="videos")$("#video-dialog").showModal();if(b.dataset.actionView==="photos")$("#photo-input").click()});$("#mobile-menu").onclick=()=>{const side=$("#admin-sidebar"),open=!side.classList.contains("is-open");side.classList.toggle("is-open",open);$("#mobile-menu").setAttribute("aria-expanded",String(open))};$("#mobile-add").onclick=()=>activateView("results");$("#profile-form").addEventListener("input",updateProfilePreview);$("#profile-form").onsubmit=e=>{e.preventDefault();state.profile=profileFromForm();recalculateResults();markDirty("profile");markDirty("results");renderStats();showStatus("Testi e profilo salvati in bozza")};$("#result-search").oninput=renderResults;$("#result-year-filter").onchange=renderResults;$("#add-result").onclick=()=>openResult();$("#add-result-line").onclick=()=>addResultLine();$("#save-result").onclick=e=>{e.preventDefault();if(saveResult())$("#result-dialog").close()};$("#add-video").onclick=()=>{$("#video-form").reset();$("#video-dialog").showModal()};$("#save-video").onclick=e=>{e.preventDefault();if(saveVideo())$("#video-dialog").close()};$("#photo-select").onclick=()=>$("#photo-input").click();$("#photo-input").onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){showStatus("La foto supera 20 MB",true);return}state.pendingPhoto=file;$("#photo-form").reset();$("#photo-form").elements.anno.value=new Date().getFullYear();$("#photo-preview").src=URL.createObjectURL(file);$("#photo-dialog").showModal()};$("#save-photo").onclick=async e=>{e.preventDefault();if(await savePhoto())$("#photo-dialog").close()};$("#publish-button").onclick=()=>$("#publish-dialog").showModal();$("#confirm-publish").onclick=e=>{e.preventDefault();publish()};$("#logout-button").onclick=()=>window.ariannaIdentity.logout();$("#login-button").onclick=()=>window.ariannaIdentity.open("login")}
function authenticated(user){state.user=user;$("#login-screen").hidden=true;$("#admin-shell").hidden=false;const name=user.user_metadata?.full_name||user.email||"Account autorizzato";$("#account-name").textContent=name;$("#account-avatar").textContent=name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();$("#greeting").textContent=`Buonasera, ${name.split(/\s+/)[0]}`;loadContent().catch(error=>showStatus(error.message,true))}
function initIdentity(){const identity=window.ariannaIdentity;identity.on("login",user=>{identity.close();authenticated(user)});identity.on("logout",()=>{localStorage.removeItem("gotrue.user");location.reload()});const user=identity.currentUser();if(user)authenticated(user)}
bind();window.addEventListener("arianna:identity-ready",initIdentity,{once:true});if(window.ariannaIdentity)initIdentity();