const state={profile:null,results:null,media:null,original:{},dirty:new Set(),user:null,pendingPhoto:null};
const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const api=async(path,options={})=>{const user=window.ariannaIdentity?.currentUser();const token=await user?.jwt();const response=await fetch(`/.netlify/functions/${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...options.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Operazione non riuscita");return body};
const showStatus=(message,error=false)=>{const el=$("#global-status");el.textContent=message;el.classList.toggle("is-error",error);el.classList.add("is-visible");clearTimeout(showStatus.timer);showStatus.timer=setTimeout(()=>el.classList.remove("is-visible"),4200)};
const clone=value=>JSON.parse(JSON.stringify(value));
const markDirty=(key)=>{state.dirty.add(key);localStorage.setItem(`arianna-draft-${key}`,JSON.stringify(state[key]));renderChanges();$("#publish-button").disabled=false};
const clearDrafts=()=>{["profile","results","media"].forEach(k=>localStorage.removeItem(`arianna-draft-${k}`));state.dirty.clear();$("#publish-button").disabled=true;renderChanges()};

function activateView(name){$$('[data-view]').forEach(b=>{b.toggleAttribute('aria-current',b.dataset.view===name);if(b.dataset.view===name)b.setAttribute('aria-current','page')});$$('.admin-view').forEach(v=>v.classList.toggle('is-active',v.id===`view-${name}`));const active=$(`#view-${name}`);$("#view-title").textContent=active?.dataset.title||"Console";$("#admin-sidebar").classList.remove("is-open");$("#mobile-menu").setAttribute("aria-expanded","false");window.scrollTo({top:0,behavior:"smooth"})}

async function loadContent(){showStatus("Caricamento dei contenuti…");const data=await api("admin-content");state.original={profile:clone(data.profile),results:clone(data.results),media:clone(data.media)};["profile","results","media"].forEach(key=>{const draft=localStorage.getItem(`arianna-draft-${key}`);state[key]=draft?JSON.parse(draft):clone(data[key]);if(draft)state.dirty.add(key)});fillProfile();renderResults();renderMedia();renderStats();renderCounts();renderChanges();$("#publish-button").disabled=state.dirty.size===0;showStatus(state.dirty.size?"Bozze locali ripristinate":"Contenuti aggiornati")}

function fillProfile(){const f=$("#profile-form");Object.entries(state.profile||{}).forEach(([key,value])=>{const field=f.elements.namedItem(key);if(field&&!Array.isArray(value))field.value=value??""});updateProfilePreview()}
function profileFromForm(){const f=$("#profile-form");const next={...state.profile};["name","category","club","coach","discipline","summary","origin"].forEach(k=>next[k]=f.elements.namedItem(k).value.trim());next.startedIn=Number(f.elements.namedItem("startedIn").value)||state.profile.startedIn;return next}
function updateProfilePreview(){const p=profileFromForm();$("#profile-preview-name").textContent=p.name;$("#profile-preview-summary").textContent=p.summary;$("#profile-preview-discipline").textContent=p.discipline;$("#profile-preview-category").textContent=p.category}

function flattenResults(){return (state.results?.resultsByYear||[]).flatMap((group,yearIndex)=>group.competitions.map((competition,competitionIndex)=>({year:group.year,yearIndex,competitionIndex,...competition})))}
function renderResults(){const rows=flattenResults();const yearSelect=$("#result-year-filter");const selected=yearSelect.value;yearSelect.innerHTML='<option value="">Tutti gli anni</option>'+[...new Set(rows.map(r=>r.year))].sort((a,b)=>b-a).map(y=>`<option>${y}</option>`).join("");yearSelect.value=selected;const query=$("#result-search").value.toLowerCase();const year=yearSelect.value;const filtered=rows.filter(r=>(!year||String(r.year)===year)&&(!query||`${r.event} ${r.place}`.toLowerCase().includes(query)));$("#results-table").innerHTML=filtered.map(r=>`<tr><td>${r.year}</td><td>${escapeHtml(r.event)}</td><td>${escapeHtml(r.place||"—")}</td><td><div class="medal-badges">${r.results.map(x=>`<span class="medal-badge">${medalLabel(x.medal)} · ${escapeHtml(x.discipline)}</span>`).join("")}</div></td><td><div class="table-actions"><button type="button" data-edit-result="${r.yearIndex}:${r.competitionIndex}">Modifica</button><button type="button" data-archive-result="${r.yearIndex}:${r.competitionIndex}">Archivia</button></div></td></tr>`).join("");$("#results-empty").hidden=filtered.length>0;$$('[data-edit-result]').forEach(b=>b.onclick=()=>openResult(...b.dataset.editResult.split(':').map(Number)));$$('[data-archive-result]').forEach(b=>b.onclick=()=>archiveResult(...b.dataset.archiveResult.split(':').map(Number)))}
function medalLabel(medal){return medal==="gold"?"Oro":medal==="silver"?"Argento":medal==="bronze"?"Bronzo":"Piazzamento"}
function addResultLine(value={discipline:"",medal:"gold"}){const row=document.createElement("div");row.className="result-line";row.innerHTML=`<input name="discipline" aria-label="Disciplina" value="${escapeHtml(value.discipline)}" required><select name="medal" aria-label="Medaglia"><option value="gold">Oro</option><option value="silver">Argento</option><option value="bronze">Bronzo</option><option value="placement">Piazzamento</option></select><button type="button" aria-label="Rimuovi disciplina">×</button>`;row.querySelector("select").value=value.medal;row.querySelector("button").onclick=()=>row.remove();$("#result-lines").append(row)}
function openResult(yearIndex=-1,competitionIndex=-1){const form=$("#result-form");form.reset();$("#result-lines").innerHTML="";form.elements.yearIndex.value=yearIndex;form.elements.competitionIndex.value=competitionIndex;if(yearIndex>=0){const group=state.results.resultsByYear[yearIndex],item=group.competitions[competitionIndex];form.elements.year.value=group.year;form.elements.event.value=item.event;form.elements.place.value=item.place||"";item.results.forEach(addResultLine);$("#result-dialog-title").textContent="Modifica risultato"}else{form.elements.year.value=new Date().getFullYear();addResultLine();$("#result-dialog-title").textContent="Aggiungi risultato"}$("#result-dialog").showModal()}
function saveResult(){const f=$("#result-form");if(!f.reportValidity())return false;const year=Number(f.elements.year.value);const item={event:f.elements.event.value.trim(),place:f.elements.place.value.trim(),results:$$('.result-line',f).map(row=>({discipline:row.querySelector('[name=discipline]').value.trim(),medal:row.querySelector('[name=medal]').value}))};const yi=Number(f.elements.yearIndex.value),ci=Number(f.elements.competitionIndex.value);if(yi>=0){const oldYear=state.results.resultsByYear[yi];if(oldYear.year===year)oldYear.competitions[ci]=item;else{oldYear.competitions.splice(ci,1);addCompetition(year,item)}}else addCompetition(year,item);state.results.resultsByYear=state.results.resultsByYear.filter(y=>y.competitions.length).sort((a,b)=>a.year-b.year);recalculateResults();markDirty("results");renderResults();renderStats();renderCounts();showStatus("Risultato salvato in bozza");return true}
function addCompetition(year,item){let group=state.results.resultsByYear.find(y=>y.year===year);if(!group){group={year,totals:{gold:0,silver:0,bronze:0},competitions:[]};state.results.resultsByYear.push(group)}group.competitions.push(item)}
function archiveResult(yi,ci){if(!confirm("Archiviare questa competizione? Potrai recuperarla dalla cronologia Git."))return;state.results.resultsByYear[yi].competitions.splice(ci,1);state.results.resultsByYear=state.results.resultsByYear.filter(y=>y.competitions.length);recalculateResults();markDirty("results");renderResults();renderStats();renderCounts();showStatus("Competizione archiviata nella bozza")}
function recalculateResults(){let gold=0,silver=0,bronze=0;for(const group of state.results.resultsByYear){const totals={gold:0,silver:0,bronze:0};group.competitions.flatMap(c=>c.results).forEach(r=>{if(totals[r.medal]!==undefined)totals[r.medal]++});group.totals=totals;gold+=totals.gold;silver+=totals.silver;bronze+=totals.bronze}const total=gold+silver+bronze;state.results.medalSummary={gold,silver,bronze,total};const competitions=state.results.resultsByYear.reduce((n,y)=>n+y.competitions.length,0);const years=Math.max(1,new Date().getFullYear()-(state.profile?.startedIn||new Date().getFullYear())+1);state.results.heroStats=[{id:"years",value:String(years),label:"anni di pratica",icon:"stat-years.svg",isPlaceholder:false},{id:"competitions",value:String(competitions),label:"competizioni",icon:"stat-trophy.svg",isPlaceholder:false},{id:"medals",value:String(total),label:"medaglie vinte",icon:"stat-medal-silver.svg",isPlaceholder:false},{id:"gold",value:String(gold),label:"medaglie d'oro",icon:"stat-medal.svg",isPlaceholder:false}]}

function youtubeId(url){try{const u=new URL(url);if(u.hostname.includes("youtu.be"))return u.pathname.slice(1);if(u.pathname.startsWith("/shorts/"))return u.pathname.split("/")[2];return u.searchParams.get("v")}catch{return null}}
function renderMedia(){const photos=(state.media||[]).filter(m=>m.tipo==="foto"&&m.visibile&&!m.isPlaceholder),videos=(state.media||[]).filter(m=>m.tipo==="video");$("#photos-grid").innerHTML=photos.map(m=>`<article class="media-card"><img src="${escapeHtml(mediaUrl(m))}" alt="${escapeHtml(m.testoAlternativo||"")}"><div class="media-card-content"><strong>${escapeHtml(m.titolo)}</strong><small>${escapeHtml(m.dettaglio||"")}</small><div class="media-card-actions"><span class="status-tag">Pubblicata</span><button class="text-button" type="button" data-remove-media="${escapeHtml(m.id)}">Archivia</button></div></div></article>`).join("");$("#photos-empty").hidden=photos.length>0;$("#videos-list").innerHTML=videos.map(m=>{const id=youtubeId(m.urlYouTube);return `<article class="video-row"><img class="video-thumb" src="${id?`https://i.ytimg.com/vi/${id}/mqdefault.jpg`:""}" alt=""><span><strong>${escapeHtml(m.titolo)}</strong><small>${escapeHtml(m.dettaglio||"")} · ${m.anno||""}</small></span><div class="table-actions"><a class="text-button" href="${escapeHtml(m.urlYouTube)}" target="_blank" rel="noopener">Apri</a><button type="button" data-remove-media="${escapeHtml(m.id)}">Archivia</button></div></article>`}).join("");$("#videos-empty").hidden=videos.length>0;$$('[data-remove-media]').forEach(b=>b.onclick=()=>removeMedia(b.dataset.removeMedia))}
function mediaUrl(item){if(item.url)return item.url;if(item.immagine)return `/images/${item.immagine}`;return ""}
function removeMedia(id){if(!confirm("Archiviare questo contenuto?"))return;state.media=state.media.map(m=>m.id===id?{...m,visibile:false}:m);markDirty("media");renderMedia();renderCounts();showStatus("Contenuto archiviato nella bozza")}
function saveVideo(){const f=$("#video-form");if(!f.reportValidity())return false;const url=f.elements.urlYouTube.value.trim();if(!youtubeId(url)){showStatus("Inserisci un link YouTube valido",true);return false}const date=f.elements.data.value;state.media.unshift({id:`video-${Date.now()}`,tipo:"video",titolo:f.elements.titolo.value.trim(),dettaglio:f.elements.dettaglio.value.trim(),data:date||undefined,anno:date?Number(date.slice(0,4)):new Date().getFullYear(),categoria:f.elements.categoria.value,urlYouTube:url,inEvidenza:f.elements.inEvidenza.checked,visibile:true});markDirty("media");renderMedia();renderCounts();showStatus("Video salvato in bozza");return true}

async function optimizeImage(file){const bitmap=await createImageBitmap(file);const max=2560,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/webp",.84));bitmap.close();return blob}
async function savePhoto(){const f=$("#photo-form");if(!f.reportValidity())return false;const button=$("#save-photo");button.disabled=true;button.textContent="Ottimizzazione…";try{const blob=await optimizeImage(state.pendingPhoto);const safeName=`${Date.now()}-${slug(f.elements.titolo.value)}.webp`;const signed=await api("admin-media-upload",{method:"POST",body:JSON.stringify({fileName:safeName,contentType:"image/webp",size:blob.size})});await fetch(signed.uploadUrl,{method:"PUT",headers:{"Content-Type":"image/webp"},body:blob});const year=Number(f.elements.anno.value)||new Date().getFullYear();state.media.unshift({id:`foto-${Date.now()}`,tipo:"foto",titolo:f.elements.titolo.value.trim(),dettaglio:f.elements.dettaglio.value.trim(),anno:year,categoria:f.elements.categoria.value,url:signed.publicUrl,testoAlternativo:f.elements.testoAlternativo.value.trim(),inEvidenza:false,visibile:true,isPlaceholder:false});markDirty("media");renderMedia();renderCounts();showStatus("Foto caricata e salvata in bozza");return true}catch(error){showStatus(error.message,true);return false}finally{button.disabled=false;button.textContent="Carica e salva"}}

function renderStats(){if(!state.results)return;recalculateResults();$("#stats-grid").innerHTML=state.results.heroStats.map(s=>`<article class="stat-card"><span>${escapeHtml(s.value)}</span><strong>${escapeHtml(s.label)}</strong><small>Calcolo automatico</small></article>`).join("")}
function renderCounts(){if(!state.results||!state.media)return;$("#count-results").textContent=flattenResults().length;$("#count-photos").textContent=state.media.filter(m=>m.tipo==="foto"&&m.visibile&&!m.isPlaceholder).length;$("#count-videos").textContent=state.media.filter(m=>m.tipo==="video"&&m.visibile).length}
function renderChanges(){const labels={profile:"Profilo e testi",results:"Risultati e statistiche",media:"Foto e video"};const html=[...state.dirty].map(key=>`<li><span>${labels[key]}</span><span class="status-tag">Bozza</span></li>`).join("");$("#change-list").innerHTML=html;$("#publish-change-list").innerHTML=html;$("#change-list").hidden=!state.dirty.size;$("#draft-empty").hidden=!!state.dirty.size;$("#draft-count").textContent=state.dirty.size?`${state.dirty.size} ${state.dirty.size===1?"area modificata":"aree modificate"}`:"Nessuna modifica"}
async function publish(){const button=$("#confirm-publish");button.disabled=true;button.textContent="Pubblicazione…";try{const files={};for(const key of state.dirty)files[key]=state[key];const result=await api("admin-publish",{method:"POST",body:JSON.stringify({files})});clearDrafts();state.original={profile:clone(state.profile),results:clone(state.results),media:clone(state.media)};$("#publish-dialog").close();showStatus("Modifiche inviate. Il sito sarà aggiornato tra pochi minuti.");renderHistory(result.commitUrls||[])}catch(error){showStatus(`${error.message}. Il sito online è rimasto invariato e la bozza è al sicuro.`,true)}finally{button.disabled=false;button.textContent="Conferma e pubblica"}}
function renderHistory(urls){if(!urls.length)return;$("#history-list").innerHTML=`<li><span><strong>Pubblicazione inviata</strong><small>${new Date().toLocaleString("it-IT")}</small></span><span class="status-tag">Completata</span></li>`}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function slug(value){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||"foto"}

function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>activateView(b.dataset.view));$$('[data-action-view]').forEach(b=>b.onclick=()=>{activateView(b.dataset.actionView);if(b.dataset.actionView==="results")openResult();if(b.dataset.actionView==="videos")$("#video-dialog").showModal();if(b.dataset.actionView==="photos")$("#photo-input").click()});$("#mobile-menu").onclick=()=>{const side=$("#admin-sidebar"),open=!side.classList.contains("is-open");side.classList.toggle("is-open",open);$("#mobile-menu").setAttribute("aria-expanded",String(open))};$("#mobile-add").onclick=()=>activateView("results");$("#profile-form").addEventListener("input",updateProfilePreview);$("#profile-form").onsubmit=e=>{e.preventDefault();state.profile=profileFromForm();recalculateResults();markDirty("profile");markDirty("results");renderStats();showStatus("Profilo salvato in bozza")};$("#result-search").oninput=renderResults;$("#result-year-filter").onchange=renderResults;$("#add-result").onclick=()=>openResult();$("#add-result-line").onclick=()=>addResultLine();$("#save-result").onclick=e=>{e.preventDefault();if(saveResult())$("#result-dialog").close()};$("#add-video").onclick=()=>{$("#video-form").reset();$("#video-dialog").showModal()};$("#save-video").onclick=e=>{e.preventDefault();if(saveVideo())$("#video-dialog").close()};$("#photo-select").onclick=()=>$("#photo-input").click();$("#photo-input").onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){showStatus("La foto supera 20 MB",true);return}state.pendingPhoto=file;$("#photo-form").reset();$("#photo-form").elements.anno.value=new Date().getFullYear();$("#photo-preview").src=URL.createObjectURL(file);$("#photo-dialog").showModal()};$("#save-photo").onclick=async e=>{e.preventDefault();if(await savePhoto())$("#photo-dialog").close()};$("#publish-button").onclick=()=>$("#publish-dialog").showModal();$("#confirm-publish").onclick=e=>{e.preventDefault();publish()};$("#logout-button").onclick=()=>window.ariannaIdentity.logout();$("#login-button").onclick=()=>window.ariannaIdentity.open("login")}
function authenticated(user){state.user=user;$("#login-screen").hidden=true;$("#admin-shell").hidden=false;const name=user.user_metadata?.full_name||user.email||"Account autorizzato";$("#account-name").textContent=name;$("#account-avatar").textContent=name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();$("#greeting").textContent=`Buonasera, ${name.split(/\s+/)[0]}`;loadContent().catch(error=>showStatus(error.message,true))}
function initIdentity(){const identity=window.ariannaIdentity;identity.on("login",user=>{identity.close();authenticated(user)});identity.on("logout",()=>{localStorage.removeItem("gotrue.user");location.reload()});const user=identity.currentUser();if(user)authenticated(user)}
bind();window.addEventListener("arianna:identity-ready",initIdentity,{once:true});if(window.ariannaIdentity)initIdentity();
